include: "https://gitlab.ndp-systemes.fr/odoo-addons/ci-files/raw/master/default-gitlab-ci.yml"

variables:
  ODOO_VERSION: "8.0"
  ODOO_DEPENDS: "odoo-addons/community-addons"
  ODOO_MODULE: "ALL"
  ODOO_IMG: "8.0-ndp"
  VERBOSE: "True"

lint_flake8:
  allow_failure: true
