image: ndpsystemes/odoo-ci:apr-ci
stages:
  - test
  - preview
  - deploy

before_script:
  - sh /init.sh

variables:
  ODOO_VERSION: "9.0"
  GIT_STRATEGY: none
  ODOO_DEPENDS: ''
  ODOO_MODULE: ALL

lint_flake8:
  stage: test
  variables:
    GIT_STRATEGY: clone
  script:
    - /run.sh
  tags:
    - test

runbot:
  stage: test
  script:
    - /run.sh
  tags:
    - test

preview_odoo:
  stage: preview
  script:
    - /run.sh
  environment:
    name: preview/$CI_BUILD_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.ndp-systemes.fr
    on_stop: stop_preview_odoo
  when: manual
  tags:
    - preview
  only:
    - gitlab_ci

stop_preview_odoo:
  stage: preview
  script:
    - /run.sh
  when: manual
  tags:
    - preview
  environment:
    name: preview/$CI_BUILD_REF_NAME
    action: stop
  only:
    - gitlab_ci
