image: ndpsystemes/odoo-ci
stages:
  - test
  - preview
  - deploy

before_script:
  - sh /init.sh

variables:
  ODOO_VERSION: "8.0"
  GIT_STRATEGY: "clone"
  ODOO_DEPENDS: "odoo-addons/community-addons"
  ODOO_MODULE: "ALL"
  ODOO_IMG: "8.0-production"

lint_flake8:
  stage: test
  script:
    - /run.sh
  tags:
    - lint
  allow_failure: true

runbot:
  stage: test
  script:
    - /run.sh
  tags:
    - runbot
